services:
  front-end-dev:
    image: front-end-dev
    restart: always
    build: ./front-end-dev/
    container_name: front-end-dev
    ports:
      - "1339:1339"
      - "8082:8082"
    volumes:
      - sharedv:/root/shared
    depends_on:
      - back-end-dev
      - studio
    networks:
      - front-end-network

  back-end-dev:
    image: back-end-dev
    restart: always
    build: ./back-end-dev/
    container_name: back-end-dev
    ports:
      - "8080:8080"
      - "1337:1337"
    volumes:
      - sharedv:/root/shared
    depends_on:
      - postgres
    networks:
      - back-end-network
      - front-end-network
    environment:
      - DATABASE_URL
      - FT_APP_ID
      - FT_APP_SECRET
      - FT_REDIRECT_URI
      - GOOGLE_CLIENT_ID
      - GOOGLE_REDIRECT_URI
      - GOOGLE_SECRET
      - JWT_SECRET
      - NODE_VERSION
      - POSTGRES_HOST
      - POSTGRES_NAME
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_USER
      - PRIVATE_KEY_PATH
      - PUBLIC_CERT_PATH
      - JWT_REFRESH_SECRET
      - REFRESH_TOKEN_KEY
      - ACCESS_TOKEN_KEY
      - TWO_FACTOR_AUTHENTICATION_APP_NAME
      - HOME_URL
      - LOGIN_URL
      - SETUP_URL
      - TFA_URL
      - DEFAULT_AVATAR

  studio:
    image: studio
    restart: always
    build: ./studio/
    container_name: studio
    ports:
      - "5555:5555"
    volumes:
      - sharedv:/root/shared
    depends_on:
      - postgres
    networks:
      - back-end-network
    environment:
      - DATABASE_URL
      - FT_APP_ID
      - FT_APP_SECRET
      - FT_REDIRECT_URI
      - GOOGLE_CLIENT_ID
      - GOOGLE_REDIRECT_URI
      - GOOGLE_SECRET
      - JWT_SECRET
      - NODE_VERSION
      - POSTGRES_HOST
      - POSTGRES_NAME
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_USER
      - PRIVATE_KEY_PATH
      - PUBLIC_CERT_PATH
      - JWT_REFRESH_SECRET
      - REFRESH_TOKEN_KEY
      - ACCESS_TOKEN_KEY
      - TWO_FACTOR_AUTHENTICATION_APP_NAME
      - HOME_URL
      - LOGIN_URL
      - SETUP_URL
      - TFA_URL
      - DEFAULT_AVATAR

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - back-end-network
    environment:
      - POSTGRES_HOST
      - POSTGRES_NAME
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_DB


networks:
  back-end-network:
    driver: bridge
    name: back-end-network
  front-end-network:
    driver: bridge
    name: front-end-network


volumes:
  sharedv:
    name: sharedv
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/.."
  postgres:
    name: postgres
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/dev-ops/volumes/database"
