services:
  front-end-dev:
    env_file: ../back-end/.env
    image: front-end-dev
    restart: always
    build: ./front-end-dev/
    container_name: front-end-dev
    ports:
      - "1339:1339"
      - "8082:8082"
    volumes:
      - sharedv:/root/shared
    depends_on:
      - back-end-dev
    networks:
      - front-end-network

  back-end-dev:
    env_file: ../back-end/.env
    image: back-end-dev
    restart: always
    build: ./back-end-dev/
    container_name: back-end-dev
    ports:
      - "8080:8080"
      - "1337:1337"
    volumes:
      - sharedv:/root/shared
    depends_on:
      - postgres
    networks:
      - back-end-network
      - front-end-network

  postgres:
    image: postgres
    restart: always
    env_file: ../back-end/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - back-end-network


networks:
  back-end-network:
    driver: bridge
    name: back-end-network
  front-end-network:
    driver: bridge
    name: front-end-network


volumes:
  sharedv:
    name: sharedv
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/.."
  postgres:
    name: postgres
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$PWD/dev-ops/volumes/database"
